import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { Button } from '@mui/material';
import SuccessModal from '../components/SuccessModal'
import { ICategory, IMovie } from '../types'
import MoviesList from '../components/MoviesList'

const Home: NextPage = () => {
  const [categories, setCategories] = useState<ICategory[]>([])
  const [selectedNominee, setSelectedNominee] = useState<ICategory[]>([])
  const [open, setOpen] = useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);

  useEffect(() => {
    const fetchData = async () => {
      const res = await (await fetch('http://localhost:3000/api/ballots')).json()
      setCategories(res?.items)
      setSelectedNominee(res?.items?.map((i: IMovie) => ({ ...i, items: [] })))
    }
    // Fetch awards data
    fetchData()
  }, [])

  const onSelectNominee = (category: string, movie: IMovie) => {
    const data: ICategory[] = [...selectedNominee]
    const categoryObj = data.find(f => f?.id === category)?.items
    if (!categoryObj) return
    // Clear selected nominee list if movie is already selected
    if (categoryObj.includes(movie)) {
      categoryObj.length = 0
    } else if (categoryObj?.length < 1) {
      categoryObj?.push(movie)
    }
    setSelectedNominee(data)
  }

  const onSubmitHandler = () => {
    // Show success modal when there is atleast one movie selected per category
    if (selectedNominee.every((f: any) => f.items.length === 1)) {
      handleOpen()
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.pageTitle}>Awards 2021</h1>
      <MoviesList selectedNominee={selectedNominee} categories={categories} onSelectNominee={onSelectNominee} />
      <Button variant="contained" className={styles.sumbitBtn} onClick={onSubmitHandler}>Submit Ballot Button</Button>
      <SuccessModal open={open} handleClose={handleClose} result={selectedNominee} />
    </div>
  )
}

export default Home
